source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
pod 'Reachability', '~> 3.1.1'
pod 'AFNetworking', '~> 2.0'
pod 'ISO8601DateFormatter', '~> 0.6'
pod 'libPusher', '~> 1.5'
pod 'SDWebImage', '~> 3.7.1'
pod 'SVPullToRefresh', '~> 0.4.1'
pod 'TDBadgedCell', '~> 2.6'
pod 'RDVCalendarView', '~> 1.0.7'
pod "GCDWebServer", '~> 2.0'
pod 'HockeySDK', '~> 3.6.1'
pod 'TPKeyboardAvoiding', '~> 1.2.4'
pod 'MGSwipeTableCell', '~> 1.2'
