#!/bin/sh

#
# Requires mogenerator, see http://rentzsch.github.io/mogenerator/
#

PATH="/usr/local/bin:$PATH"
export PATH

prevdir="`pwd`"

#
# Sanity checks
#

for dir in Ring/Helpers/Databases Ring/Models/Entities Ring/Models/Utilities 
do
  test -d "$dir" || { "Directory $dir not found."; exit 1; }
done

#
# Generate managed object classes
#

for db in Ring/Models/*.xcdatamodeld
do
  mogenerator -m "$db" -O Ring/Models/Entities --template-var arc=true
done

#
# Generate Models.h
#

modelsh_final="Ring/SuportingFiles/Ring-Models.h"
modelsh="$modelsh_final.tmp"

echo '// Models.h' > "$modelsh"
echo "// Auto-generated by $0" >> "$modelsh"
echo '#import "RingData.h"' >> "$modelsh"

for dir in Ring/Models/Entities Ring/Models/Utilities
do
  cd "$dir"
  for hfile in *h
  do
    echo "#import \"$hfile\""
  done
  cd "$prevdir"
done >> "$modelsh"

diff "$modelsh" "$modelsh_final" > /dev/null && rm "$modelsh" || { echo "Updating $modelsh_final"; mv "$modelsh" "$modelsh_final"; }
